In [5]:
!kaggle datasets download -d parvmodi/english-to-hindi-machine-translation-dataset

Dataset URL: https://www.kaggle.com/datasets/parvmodi/english-to-hindi-machine-translation-dataset
License(s): CC0-1.0
100% 1.04G/1.04G [00:29<00:00, 42.4MB/s]
100% 1.04G/1.04G [00:29<00:00, 37.7MB/s]


In [6]:
!unzip english-to-hindi-machine-translation-dataset.zip

Archive:  english-to-hindi-machine-translation-dataset.zip
  inflating: train.en                
  inflating: train.hi                


In [8]:
filepath_en = 'train.en'
filepath_hi = 'train.hi'

with open(filepath_en, encoding='utf-8') as file:
    lines_en = file.readlines()
print(len(lines_en))
print(lines_en[:5])

with open(filepath_hi, encoding='utf-8') as file:
    lines_hi = file.readlines()

print(len(lines_hi))
print(lines_hi[:5])

10125706
["However, Paes, who was partnering Australia's Paul Hanley, could only go as far as the quarterfinals where they lost to Bhupathi and Knowles\n", 'Whosoever desires the reward of the world, with Allah is the reward of the world and of the Everlasting Life. Allah is the Hearer, the Seer.\n', 'The value of insects in the biosphere is enormous because they outnumber all other living groups in measure of species richness.\n', 'Mithali To Anchor Indian Team Against Australia in ODIs\n', 'After the assent of the Honble President on 8thSeptember, 2016, the 101thConstitutional Amendment Act, 2016 came into existence\n']
10125706
['आस्ट्रेलिया के पाल हेनली के साथ जोड़ी बनाने वाले पेस मियामी में क्वार्टरफाइनल तक ही पहुंच सके क्योंकि इस दौर में उन्हें भूपति और नोल्स ने हराया था।\n', 'और जो शख्स (अपने आमाल का) बदला दुनिया ही में चाहता है तो ख़ुदा के पास दुनिया व आख़िरत दोनों का अज्र मौजूद है और ख़ुदा तो हर शख्स की सुनता और सबको देखता है\n', 'जैव-मंडल में कीड़ों का मूल्य बहुत है, क्योंकि प

In [9]:
TOTAL_SENTENCES = 200000
english_sentences = lines_en[:TOTAL_SENTENCES]
hindi_sentences = lines_hi[:TOTAL_SENTENCES]
english_sentences = [sentence.rstrip('\n').lower() for sentence in english_sentences]
hindi_sentences = [sentence.rstrip('\n') for sentence in hindi_sentences]

print(english_sentences[:5])
print("================================")
print(hindi_sentences[:5])

["however, paes, who was partnering australia's paul hanley, could only go as far as the quarterfinals where they lost to bhupathi and knowles", 'whosoever desires the reward of the world, with allah is the reward of the world and of the everlasting life. allah is the hearer, the seer.', 'the value of insects in the biosphere is enormous because they outnumber all other living groups in measure of species richness.', 'mithali to anchor indian team against australia in odis', 'after the assent of the honble president on 8thseptember, 2016, the 101thconstitutional amendment act, 2016 came into existence']
['आस्ट्रेलिया के पाल हेनली के साथ जोड़ी बनाने वाले पेस मियामी में क्वार्टरफाइनल तक ही पहुंच सके क्योंकि इस दौर में उन्हें भूपति और नोल्स ने हराया था।', 'और जो शख्स (अपने आमाल का) बदला दुनिया ही में चाहता है तो ख़ुदा के पास दुनिया व आख़िरत दोनों का अज्र मौजूद है और ख़ुदा तो हर शख्स की सुनता और सबको देखता है', 'जैव-मंडल में कीड़ों का मूल्य बहुत है, क्योंकि प्रजातियों की समृद्धि के मामले मे

In [10]:
import numpy as np
PERCENTILE = 97
print( f"{PERCENTILE}th percentile length Kannada: {np.percentile([len(x) for x in hindi_sentences], PERCENTILE)}" )
print( f"{PERCENTILE}th percentile length English: {np.percentile([len(x) for x in english_sentences], PERCENTILE)}" )


97th percentile length Kannada: 258.0
97th percentile length English: 267.0


In [11]:
START_TOKEN = ''
PADDING_TOKEN = ''
END_TOKEN = ''

english_vocabulary = [START_TOKEN, ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/',
                        '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
                        ':', '<', '=', '>', '?', '@',
                        '[', '\' ', ']', '^', '_', '`',
                        'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l',
                        'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x',
                        'y', 'z',
                        '{', '|', '}', '~', PADDING_TOKEN, END_TOKEN]

hindi_vocabulary = [START_TOKEN, 'अ', 'आ', 'इ', 'ई', 'उ', 'ऊ', 'ऋ', 'ए', 'ऐ', 'ओ', 'औ',
    'क', 'ख', 'ग', 'घ', 'ङ','ड़', 'च', 'छ', 'ज', 'झ', 'ञ',
    'ट', 'ठ', 'ड', 'ढ', 'ण', 'त', 'थ', 'द', 'ध', 'न',
    'प', 'फ', 'ब', 'भ', 'म', 'य', 'र', 'ल', 'व', 'श',
    'ष', 'स', 'ह', '़', 'ा', 'ि', 'ी', 'ु', 'ू', 'े', 'ै', 'ो', 'ौ',
    'ं', 'ः', 'ँ', '्', '०', '१', '२', '३', '४', '५', '६', '७', '८', '९', '|',
    ':', '<', '=', '>', '?', '@',
    '[', '\' ', ']', '^', '_', '`',
    ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/',
    '0', '1', '2', '3', '4', '5', '6', '7', '8', '9','\u200d','।', 'ृ',
    PADDING_TOKEN, END_TOKEN
]

In [12]:
max_sequence_length = 250

def is_valid_tokens(sentence, vocab):
    for token in list(set(sentence)):
        if token not in vocab:
            return False
    return True

def is_valid_length(sentence, max_sequence_length):
    return len(list(sentence)) < (max_sequence_length - 1) # need to re-add the end token so leaving 1 space

valid_sentence_indicies = []
for index in range(len(hindi_sentences)):
    hindi_sentence, english_sentence = hindi_sentences[index], english_sentences[index]
    if is_valid_length(hindi_sentence, max_sequence_length) \
      and is_valid_length(english_sentence, max_sequence_length) \
      and is_valid_tokens(hindi_sentence, hindi_vocabulary):
        valid_sentence_indicies.append(index)

print(f"Number of sentences: {len(hindi_sentences)}")
print(f"Number of valid sentences: {len(valid_sentence_indicies)}")


Number of sentences: 200000
Number of valid sentences: 151260


In [13]:
# for i in 'शख्स':
  # print(i)


# hindi_sentences = [
#     'आस्ट्रेलिया के पाल हेनली के साथ जोड़ी बनाने वाले पेस मियामी में क्वार्टरफाइनल तक ही पहुंच सके क्योंकि इस दौर में उन्हें भूपति और नोल्स ने हराया था।',
#     'और जो शख्स (अपने आमाल का) बदला दुनिया ही में चाहता है तो ख़ुदा के पास दुनिया व आख़िरत दोनों का अज्र मौजूद है और ख़ुदा तो हर शख्स की सुनता और सबको देखता है',
#     'जैव-मंडल में कीड़ों का मूल्य बहुत है, क्योंकि प्रजातियों की समृद्धि के मामले में उनकी संख्या अन्य जीव समूहों से ज़्यादा है।',
#     'आस्ट्रेलिया के खिलाफ वनडे टीम की कमान मिताली को',
#     '8 सितम्‍बर, 2016 को माननीय राष्ट्रपति की स्‍वीकृति मिलने के बाद 101वां संविधान संशोधन अधिनियम, 2016 अस्तित्व में आया'
# ]

# Define the provided vocabulary set
hindi_vocabulary_set = set(hindi_vocabulary)

# Combine all sentences into one string
combined_sentences = ''.join(hindi_sentences)

# Find all unique characters in the combined sentences
unique_chars_in_sentences = set(combined_sentences)

# Find characters in the sentences that are not in the vocabulary
missing_chars = unique_chars_in_sentences - hindi_vocabulary_set

print("Characters in the sentences not in the vocabulary:", missing_chars)


Characters in the sentences not in the vocabulary: {'ត', 'B', 'Р', '°', 'F', 'Z', '○', '\ue205', '章', 'ғ', '春', 'к', 'М', 'า', '੍', '夕', 'ড', 'ු', '׃', '“', '§', 'ல', 'Ⓡ', 'ె', 'ē', 'À', 'ன', 'E', 'Ň', 'ɑ', 'ر', '»', 'ಯ', '‘', 'ল', 'ॐ', 'ν', '਼', 'd', 'п', 'е', '́', 'Ę', 'ז', 's', 'ï', 'ֹ', 'χ', 'ล', 'แ', 'ர', '→', 'я', 'ס', 'デ', 'ං', 'Ō', 'p', 'ৱ', '”', 'ุ', 'n', '\uf0d8', 'ế', 'g', '\xa0', 'ා', '現', 'b', 'コ', 'ː', 'ස', 'ज़', 'レ', '‚', '▪', 'τ', 'ำ', 'ុ', '郑', 'ی', 'ช', 'л', '≈', 'α', 'ಳ', 'ع', 'য', 'כ', '女', 'J', ';', 'ි', 'ŋ', 'É', 'ל', 'ท', '日', '鲁', 'ಮ', 'স', 'Я', 'ַ', 'ঔ', 'i', 'ల', 'מ', '¨', 'K', 'м', 'ී', '\\', '॥', 'ئ', '\xad', 'Ṭ', '庭', 'א', '\uf0a7', 'פ', 'm', 'Э', 'с', 'ĺ', '‑', '▫', 'ট', '林', 'ய', 'ऩ', '¼', 'ॊ', 'េ', 'ス', '班', 'ு', 'ɪ', 'క', 'ก', '世', 'ə', 'ᠠ', 'Ż', 'ā', 'ؤ', 'ɵ', '七', 'Ž', 'إ', '☞', '唐', '自', '{', 'С', '動', 'ऽ', 'গ', 'ง', '車', 'ৰ', 'U', 'ে', '♪', 'ූ', '◆', 'ಚ', 'æ', 'প', 'ص', 'ֵ', 'ව', 'ィ', 'λ', '’', '\u200b', 'Þ', '长', 'ক', 'ా', 'ী', 'ң', 'ো', 'υ', 'ऑ', '

In [14]:
index_to_hindi = {k:v for k,v in enumerate(hindi_vocabulary)}
hindi_to_index = {v:k for k,v in enumerate(hindi_vocabulary)}
index_to_english = {k:v for k,v in enumerate(english_vocabulary)}
english_to_index = {v:k for k,v in enumerate(english_vocabulary)}

In [41]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding, Dropout
from tensorflow.keras import layers
import numpy as np

class PositionalEncoding(tf.keras.layers.Layer):
    def __init__(self, d_model, max_seq_len):
        super(PositionalEncoding, self).__init__()
        self.d_model = d_model
        self.max_seq_len = max_seq_len

    def call(self, inputs):
        pos = np.arange(self.max_seq_len)[:, np.newaxis]
        i = np.arange(self.d_model)[np.newaxis, :]
        angle_rates = 1 / np.power(10000, (2 * (i // 2)) / np.float32(self.d_model))
        angle_rads = pos * angle_rates
        angle_rads[:, 0::2] = np.sin(angle_rads[:, 0::2])
        angle_rads[:, 1::2] = np.cos(angle_rads[:, 1::2])
        pos_encoding = angle_rads[np.newaxis, ...]
        return tf.constant(pos_encoding, dtype=tf.float32)

class SentenceEmbedding(tf.keras.Model):
    def __init__(self, max_sequence_length, d_model, language_to_index, START_TOKEN, END_TOKEN, PADDING_TOKEN):
        super(SentenceEmbedding, self).__init__()
        self.vocab_size = len(language_to_index)
        self.max_sequence_length = max_sequence_length
        self.embedding = Embedding(input_dim=self.vocab_size, output_dim=d_model)
        self.language_to_index = language_to_index
        self.position_encoder = PositionalEncoding(d_model, max_sequence_length)
        self.dropout = Dropout(0.1)
        self.START_TOKEN = START_TOKEN
        self.END_TOKEN = END_TOKEN
        self.PADDING_TOKEN = PADDING_TOKEN

    def batch_tokenize(self, batch, start_token, end_token):
        def tokenize(sentence, start_token, end_token):
            sentence = sentence.numpy().decode('utf-8').split()  # Convert tensor to list of strings
            sentence_word_indices = [self.language_to_index.get(token, self.language_to_index.get('<UNK>')) for token in sentence]
            # sentence_word_indices = [self.language_to_index[token] for token in list(sentence)]
            if start_token:
                sentence_word_indices.insert(0, self.language_to_index[self.START_TOKEN])
            if end_token:
                sentence_word_indices.append(self.language_to_index[self.END_TOKEN])
            sentence_word_indices.extend([self.language_to_index[self.PADDING_TOKEN]] * (self.max_sequence_length - len(sentence_word_indices)))
            return tf.convert_to_tensor(sentence_word_indices, dtype=tf.int32)

        tokenized = [tokenize(sentence, start_token, end_token) for sentence in batch]
        return tf.stack(tokenized)

    def call(self, x, start_token, end_token):
        x = self.batch_tokenize(x, start_token, end_token)
        x = self.embedding(x)
        pos = self.position_encoder(x)
        x = self.dropout(x + pos)
        return x


In [39]:
def is_valid_tokens(sentence, vocab):
    for token in list(set(sentence)):
        if token not in vocab:
            return False
    return True

def is_valid_length(sentence, max_sequence_length):
    return len(list(sentence)) < (max_sequence_length - 1) # need to re-add the end token so leaving 1 space

valid_english_sentences = []
for index in range(len(english_sentences)):
    english_sentence =  english_sentences[index]
    if  is_valid_length(english_sentence, max_sequence_length) \
      and is_valid_tokens(english_sentence, english_vocabulary):
        valid_english_sentences.append(english_sentence)


def batch_tokenize(language_to_index, batch, start_token, end_token, START_TOKEN, END_TOKEN, PADDING_TOKEN, max_sequence_length):
    def tokenize(sentence, start_token, end_token):
        sentence_word_indices = [language_to_index[token] for token in list(sentence)]
        if start_token:
            sentence_word_indices.insert(0, language_to_index[START_TOKEN])
        if end_token:
            sentence_word_indices.append(language_to_index[END_TOKEN])
        sentence_word_indices.extend([language_to_index[PADDING_TOKEN]] * (max_sequence_length - len(sentence_word_indices)))
        return tf.convert_to_tensor(sentence_word_indices, dtype=tf.int32)

    tokenized = [tokenize(sentence, start_token, end_token) for sentence in batch]
    return tf.stack(tokenized)

x = batch_tokenize(language_to_index = english_to_index, batch = valid_english_sentences[:10], start_token = True, end_token = True,
                     START_TOKEN= START_TOKEN, END_TOKEN= END_TOKEN, PADDING_TOKEN=PADDING_TOKEN, max_sequence_length= max_sequence_length)

print(x)
# print(valid_english_sentences)
# count_70 = tf.math.count_nonzero(res[0] == 70)

# print(count_70)


tf.Tensor(
[[70 46 53 ... 70 70 70]
 [70 61 46 ... 70 70 70]
 [70 58 46 ... 70 70 70]
 ...
 [70 39 57 ... 70 70 70]
 [70 48 46 ... 70 70 70]
 [70 39 56 ... 70 70 70]], shape=(10, 250), dtype=int32)


In [40]:
import tensorflow as tf

d_model = 512

sentence_embedding = SentenceEmbedding(
    max_sequence_length=max_sequence_length,
    d_model=d_model,
    language_to_index=english_to_index,
    START_TOKEN=START_TOKEN,
    END_TOKEN=END_TOKEN,
    PADDING_TOKEN=PADDING_TOKEN
)

# output = sentence_embedding(valid_english_sentences[:10], start_token=True, end_token=True)

# print(output)

AttributeError: Exception encountered when calling layer 'sentence_embedding_8' (type SentenceEmbedding).

'str' object has no attribute 'numpy'

Call arguments received by layer 'sentence_embedding_8' (type SentenceEmbedding):
  • x=['"however, paes, who was partnering australia\'s paul hanley, could only go as far as the quarterfinals where they lost to bhupathi and knowles"', "'whosoever desires the reward of the world, with allah is the reward of the world and of the everlasting life. allah is the hearer, the seer.'", "'the value of insects in the biosphere is enormous because they outnumber all other living groups in measure of species richness.'", "'mithali to anchor indian team against australia in odis'", "'after the assent of the honble president on 8thseptember, 2016, the 101thconstitutional amendment act, 2016 came into existence'", "'the court has fixed a hearing for february 12'", "'please select the position where the track should be split.'", "'as per police, armys 22rr, special operation group (sog) of police and the central reserve police force (crpf) cordoned the village and launched search operation in the area.'", "'jharkhand chief minister hemant soren'", "'arvind kumar, sho of the sector 55/56 police station, said a case has been registered under section 376-d (gang rape) of the indian penal code.'"]
  • start_token=True
  • end_token=True

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense, Layer
import math

def scaled_dot_product(q, k, v, mask=None):
    d_k = tf.shape(q)[-1]
    scaled = tf.matmul(q, k, transpose_b=True) / tf.math.sqrt(tf.cast(d_k, tf.float32))
    if mask is not None:
        scaled += mask
    attention = tf.nn.softmax(scaled, axis=-1)
    values = tf.matmul(attention, v)
    return values, attention

class MultiHeadAttention(Layer):
    def __init__(self, d_model, num_heads):
        super(MultiHeadAttention, self).__init__()
        self.d_model = d_model
        self.num_heads = num_heads
        self.head_dim = d_model // num_heads
        self.qkv_layer = Dense(3 * d_model)
        self.linear_layer = Dense(d_model)

    def call(self, x, mask=None):
        batch_size = tf.shape(x)[0]
        sequence_length = tf.shape(x)[1]
        qkv = self.qkv_layer(x)
        qkv = tf.reshape(qkv, (batch_size, sequence_length, self.num_heads, 3 * self.head_dim))
        qkv = tf.transpose(qkv, perm=[0, 2, 1, 3])
        q, k, v = tf.split(qkv, num_or_size_splits=3, axis=-1)
        values, attention = scaled_dot_product(q, k, v, mask)
        values = tf.transpose(values, perm=[0, 2, 1, 3])
        values = tf.reshape(values, (batch_size, sequence_length, self.num_heads * self.head_dim))
        out = self.linear_layer(values)
        return out

multihead_attention = MultiHeadAttention(d_model= d_model, num_heads= 8)

x = multihead_attention(x= output)
x

In [ ]:
class LayerNormalization(tf.keras.layers.Layer):
    def __init__(self, parameters_shape, eps=1e-5):
        super(LayerNormalization, self).__init__()
        self.parameters_shape = parameters_shape
        self.eps = eps
        self.gamma = self.add_weight(
            shape=parameters_shape,
            initializer="ones",
            trainable=True,
            name="gamma"
        )
        self.beta = self.add_weight(
            shape=parameters_shape,
            initializer="zeros",
            trainable=True,
            name="beta"
        )

    def call(self, inputs):
        dims = [-i for i in range(1, len(self.parameters_shape) + 1)]
        mean = tf.reduce_mean(inputs, axis=dims, keepdims=True)
        var = tf.reduce_mean(tf.square(inputs - mean), axis=dims, keepdims=True)
        std = tf.sqrt(var + self.eps)
        y = (inputs - mean) / std
        out = self.gamma * y + self.beta
        return out


class PositionwiseFeedForward(tf.keras.layers.Layer):
    def __init__(self, d_model, hidden, drop_prob=0.1):
        super(PositionwiseFeedForward, self).__init__()
        self.linear1 = tf.keras.layers.Dense(hidden)
        self.linear2 = tf.keras.layers.Dense(d_model)
        self.relu = tf.keras.layers.ReLU()
        self.dropout = tf.keras.layers.Dropout(rate=drop_prob)

    def call(self, x, training=False):
        x = self.linear1(x)
        x = self.relu(x)
        x = self.dropout(x, training=training)
        x = self.linear2(x)
        return x


class EncoderLayer(tf.keras.layers.Layer):
    def __init__(self, d_model, ffn_hidden, num_heads, drop_prob):
        super(EncoderLayer, self).__init__()
        self.attention = MultiHeadAttention(d_model=d_model, num_heads=num_heads)
        self.norm1 = LayerNormalization(parameters_shape=[d_model])
        self.dropout1 = tf.keras.layers.Dropout(rate=drop_prob)
        self.ffn = PositionwiseFeedForward(d_model=d_model, hidden=ffn_hidden, drop_prob=drop_prob)
        self.norm2 = LayerNormalization(parameters_shape=[d_model])
        self.dropout2 = tf.keras.layers.Dropout(rate=drop_prob)

    def call(self, x, self_attention_mask, training=False):
        residual_x = x
        x = self.attention(x, mask=self_attention_mask)
        x = self.dropout1(x, training=training)
        x = self.norm1(x + residual_x)
        residual_x = x
        x = self.ffn(x, training=training)
        x = self.dropout2(x, training=training)
        x = self.norm2(x + residual_x)
        return x

num_heads =8
ffn_hidden = 2048
encoder_layer = EncoderLayer(d_model, ffn_hidden, num_heads, drop_prob =0.1)

x = encoder_layer(x,self_attention_mask= None)
x

In [ ]:
train_dataset = tf.data.Dataset.from_tensor_slices(valid_english_sentences)
batch_size = 32
train_dataset = train_dataset.batch(batch_size)
iterator = iter(train_dataset)
first_batch = next(iterator)
first_batch = tf.reshape(first_batch, (1,batch_size))
first_batch

In [ ]:
class SequentialEncoder(tf.keras.Sequential):
    def call(self, inputs, self_attention_mask, training=False):
        x = inputs
        for module in self.layers:
            x = module(x, self_attention_mask, training=training)
        return x


class Encoder(tf.keras.layers.Layer):
    def __init__(self,
                 d_model,
                 ffn_hidden,
                 num_heads,
                 drop_prob,
                 num_layers,
                 max_sequence_length,
                 language_to_index,
                 START_TOKEN,
                 END_TOKEN,
                 PADDING_TOKEN):
        super(Encoder, self).__init__()
        self.sentence_embedding = SentenceEmbedding(max_sequence_length, d_model, language_to_index, START_TOKEN, END_TOKEN, PADDING_TOKEN)
        self.layers = SequentialEncoder([EncoderLayer(d_model, ffn_hidden, num_heads, drop_prob)
                                      for _ in range(num_layers)])

    def call(self, x, self_attention_mask, start_token, end_token, training=False):
        x = self.sentence_embedding(x, start_token, end_token)
        x = self.layers(x, self_attention_mask, training=training)
        return x
drop_prob =0.1
encoder = Encoder(d_model =d_model,ffn_hidden=  ffn_hidden,num_heads= num_heads, drop_prob= 0.1, num_layers= 1, max_sequence_length= max_sequence_length,
                  language_to_index= english_to_index, START_TOKEN= START_TOKEN, END_TOKEN= END_TOKEN, PADDING_TOKEN= PADDING_TOKEN)
x = encoder(x= first_batch, self_attention_mask= None, start_token= True, end_token= True)
x